### PR TITLE
Merge pull request #1 from opennetworkinglab/master

### PR DESCRIPTION
**Pull request by samueljcc**
同步

### CODE REVIEW

**Comment by alshabib** [comment]
What is this pull request about?

**Comment by btarno** [comment]
I'm not sure.  My only intent was to pull down a copy of Open Daylight so I
can start playing around with it.  Did I do something wrong?

**Comment by btarno** [comment]
oops, sorry guys.  I didn't notice the list.  Forgive me...

**Comment by bocon13** [comment]
Closing this pull request. If you would like to contribute to the project, please see our wiki page about getting started: https://wiki.onosproject.org/display/ONOS/A+Beginner%27s+Guide+to+Contribution

**Pull request closed without merging**
