### PR TITLE
Refactor Copycat transport to ensure connections are properly cleaned up

### PR DESCRIPTION
**Pull request by kuujo**
This PR is a complete rewrite of the Copycat `Transport` in ONOS to improve efficiency and ensure that connections are properly closed on each side. It also fixes some issues in ONOS's `NettyMessagingManager` and adds new unit tests and test scenarios.

### CODE REVIEW

**Comment by kuujo** [comment]
Ugh didn't mean to open this against ONOS :-)

**Comment by MaoJianwei** [comment]
please push your idea to ONOS's JIRA or Gerrit

**Comment by kuujo** [comment]
Yep, thanks! It's already closed. I meant to open it on my fork.

**Comment by kuujo** [comment]
But on a related note, it does look like there are a few PRs in here that do need to be closed and pointed in the right direction...

**Comment by MaoJianwei** [comment]
ONOS use Gerrit to review code, github here is just a mirror :-)

**Pull request closed without merging**
